package com.williamcallahan.javachat.config;

import java.util.Objects;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Binds the canonical Qdrant connection settings once for every transport consumer.
 *
 * <p>Keeping the secret alongside the non-secret connection fields ensures gRPC, REST, startup
 * validation, and diagnostics cannot drift onto different property names or defaults. The class is
 * deliberately not a record so its API key is never included in an autogenerated {@code toString()}.
 */
@Component
public final class QdrantConnectionProperties {
    static final String QDRANT_HOST_PROPERTY_NAME = "spring.ai.vectorstore.qdrant.host";
    static final String QDRANT_GRPC_PORT_PROPERTY_NAME = "spring.ai.vectorstore.qdrant.port";
    static final String QDRANT_TLS_PROPERTY_NAME = "spring.ai.vectorstore.qdrant.use-tls";
    static final String QDRANT_API_KEY_ENVIRONMENT_VARIABLE_NAME = "QDRANT_API_KEY";

    private static final String QDRANT_HOST_PROPERTY = "${" + QDRANT_HOST_PROPERTY_NAME + "}";
    private static final String QDRANT_GRPC_PORT_PROPERTY = "${" + QDRANT_GRPC_PORT_PROPERTY_NAME + "}";
    private static final String QDRANT_TLS_PROPERTY = "${" + QDRANT_TLS_PROPERTY_NAME + "}";
    private static final String QDRANT_API_KEY_ENVIRONMENT_VARIABLE =
            "${" + QDRANT_API_KEY_ENVIRONMENT_VARIABLE_NAME + ":}";

    private final String host;
    private final int grpcPort;
    private final boolean useTls;
    private final String apiKey;

    /**
     * Creates the shared typed view of Qdrant connection configuration.
     *
     * @param host configured Qdrant host
     * @param grpcPort configured Qdrant gRPC port
     * @param useTls whether Qdrant transports use TLS
     * @param apiKey Qdrant credential supplied directly by the environment
     */
    public QdrantConnectionProperties(
            @Value(QDRANT_HOST_PROPERTY) String host,
            @Value(QDRANT_GRPC_PORT_PROPERTY) int grpcPort,
            @Value(QDRANT_TLS_PROPERTY) boolean useTls,
            @Value(QDRANT_API_KEY_ENVIRONMENT_VARIABLE) String apiKey) {
        this.host = Objects.requireNonNull(host, "host");
        this.grpcPort = grpcPort;
        this.useTls = useTls;
        this.apiKey = Objects.requireNonNull(apiKey, "apiKey");
    }

    /**
     * Returns the configured Qdrant host.
     *
     * @return Qdrant host
     */
    public String host() {
        return host;
    }

    /**
     * Returns the configured Qdrant gRPC port.
     *
     * @return Qdrant gRPC port
     */
    public int grpcPort() {
        return grpcPort;
    }

    /**
     * Indicates whether Qdrant transports use TLS.
     *
     * @return true when Qdrant connections use TLS
     */
    public boolean useTls() {
        return useTls;
    }

    /**
     * Returns the Qdrant API key without exposing it through object diagnostics.
     *
     * @return configured API key, which is blank when authentication is not required
     */
    public String apiKey() {
        return apiKey;
    }
}
