#!/bin/bash

JAVA_API_SOURCE_MANIFEST_HEADER='javaRelease|remoteBaseUrl|relativeMirrorPath|displayName|cutDirectories|minimumHtmlFiles|rejectRegex|allowPartial'
JAVA_API_SOURCE_MAX_INTEGER='2147483647'
JAVA_API_SOURCE_PROJECTIONS=()
DOCUMENTATION_SOURCE_MANIFEST_HEADER='fetchUrl|citationBaseUrl|relativeMirrorPath|displayName|docSet|sourceKind|docType|docVersion'
DOCUMENTATION_SOURCE_PROJECTIONS=()

is_canonical_manifest_integer() {
    local integer_text="$1"
    if [[ ! "$integer_text" =~ ^(0|[1-9][0-9]*)$ ]]; then
        return 1
    fi
    if [ "${#integer_text}" -gt "${#JAVA_API_SOURCE_MAX_INTEGER}" ]; then
        return 1
    fi
    if [ "${#integer_text}" -eq "${#JAVA_API_SOURCE_MAX_INTEGER}" ] \
        && [ "$integer_text" -gt "$JAVA_API_SOURCE_MAX_INTEGER" ]; then
        return 1
    fi
}

has_boundary_whitespace() {
    local manifest_text="$1"
    local LC_ALL=C
    [[ "$manifest_text" =~ ^[[:space:]] || "$manifest_text" =~ [[:space:]]$ ]]
}

has_manifest_control_character() {
    local manifest_text="$1"
    local LC_ALL=C
    [[ "$manifest_text" == *[[:cntrl:]]* ]]
}

is_absolute_https_remote_base_url() {
    local remote_base_url="$1"
    if [[ "$remote_base_url" != https://* || "$remote_base_url" != */ ]]; then
        return 1
    fi
    if [[ "$remote_base_url" == *[[:space:]]* || "$remote_base_url" == *\\* ]]; then
        return 1
    fi

    local remote_authority_and_path="${remote_base_url#https://}"
    local remote_authority="${remote_authority_and_path%%[/?#]*}"
    if [ -z "$remote_authority" ]; then
        return 1
    fi

    local remote_host_and_port="${remote_authority##*@}"
    if [ -z "$remote_host_and_port" ]; then
        return 1
    fi
    if [[ "$remote_host_and_port" == \[* ]]; then
        [[ "$remote_host_and_port" =~ ^\[[0-9A-Fa-f:.]+\](:[0-9]+)?$ ]]
        return
    fi
    [[ "$remote_host_and_port" =~ ^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(:[0-9]+)?$ ]]
}

is_normalized_relative_mirror_path() {
    local relative_mirror_path="$1"
    if [[ "$relative_mirror_path" == /* \
        || "$relative_mirror_path" == */ \
        || "$relative_mirror_path" == *//* \
        || "$relative_mirror_path" == *\\* ]]; then
        return 1
    fi

    local IFS='/'
    local -a mirror_path_segments
    read -r -a mirror_path_segments <<< "$relative_mirror_path"
    local mirror_path_segment
    for mirror_path_segment in "${mirror_path_segments[@]}"; do
        if [ -z "$mirror_path_segment" ] \
            || [ "$mirror_path_segment" = "." ] \
            || [ "$mirror_path_segment" = ".." ]; then
            return 1
        fi
    done
}

is_blank_manifest_line() {
    local manifest_line="$1"
    local LC_ALL=C
    [[ "$manifest_line" =~ ^[[:space:]]*$ ]]
}

count_html_files() {
    local directory_path="$1"
    if [ -d "$directory_path" ]; then
        find "$directory_path" -name "*.html" 2>/dev/null | wc -l | tr -d ' '
    else
        echo "0"
    fi
}

extract_javadoc_comment_version() {
    local file_path="$1"
    if [ -z "$file_path" ] || [ ! -f "$file_path" ]; then
        echo ""
        return 0
    fi
    local line
    line="$(grep -E '<!-- Generated by javadoc \\([0-9]+' "$file_path" 2>/dev/null | head -n 1 || true)"
    if [ -z "$line" ]; then
        echo ""
        return 0
    fi
    echo "$line" | sed -E 's/.*javadoc \\(([0-9]+)\\).*/\\1/'
}

load_java_api_documentation_sources() {
    local source_manifest_file="$1"
    if [ ! -f "$source_manifest_file" ]; then
        echo "Java API source manifest not found: $source_manifest_file" >&2
        return 1
    fi

    JAVA_API_SOURCE_PROJECTIONS=()
    local manifest_header=""
    local expected_delimiter_count=-1
    local manifest_line_number=0
    local manifest_line
    local retained_java_releases=("")
    local retained_relative_mirror_paths=("")
    while IFS= read -r manifest_line || [ -n "$manifest_line" ]; do
        manifest_line_number=$((manifest_line_number + 1))
        manifest_line="${manifest_line%$'\r'}"
        if [ "$manifest_line_number" -eq 1 ]; then
            manifest_header="$manifest_line"
            if [ -z "$manifest_header" ]; then
                echo "Java API source manifest header cannot be blank: $source_manifest_file" >&2
                return 1
            fi
            if [ "$manifest_header" != "$JAVA_API_SOURCE_MANIFEST_HEADER" ]; then
                echo "Java API source manifest header is invalid: $source_manifest_file" >&2
                return 1
            fi
            local header_delimiters="${manifest_header//[^|]/}"
            expected_delimiter_count=${#header_delimiters}
            continue
        fi
        if is_blank_manifest_line "$manifest_line"; then
            echo "Java API source manifest line $manifest_line_number cannot be blank" >&2
            return 1
        fi

        local source_delimiters="${manifest_line//[^|]/}"
        if [ "${#source_delimiters}" -ne "$expected_delimiter_count" ]; then
            echo "Java API source manifest line $manifest_line_number has an invalid column count" >&2
            return 1
        fi

        local javaRelease
        local remoteBaseUrl
        local relativeMirrorPath
        local displayName
        local cutDirectories
        local minimumHtmlFiles
        local rejectRegex
        local allowPartial
        IFS='|' read -r javaRelease remoteBaseUrl relativeMirrorPath displayName cutDirectories minimumHtmlFiles rejectRegex allowPartial <<< "$manifest_line"

        if ! is_canonical_manifest_integer "$javaRelease" || [ "$javaRelease" = "0" ]; then
            echo "Java API source manifest line $manifest_line_number has an invalid Java release" >&2
            return 1
        fi
        if [ -z "$remoteBaseUrl" ] || [ -z "$relativeMirrorPath" ] || [ -z "$displayName" ]; then
            echo "Java API source manifest line $manifest_line_number has a blank required field" >&2
            return 1
        fi
        if has_boundary_whitespace "$remoteBaseUrl" \
            || has_boundary_whitespace "$relativeMirrorPath" \
            || has_boundary_whitespace "$displayName" \
            || has_boundary_whitespace "$rejectRegex" \
            || has_manifest_control_character "$remoteBaseUrl" \
            || has_manifest_control_character "$relativeMirrorPath" \
            || has_manifest_control_character "$displayName" \
            || has_manifest_control_character "$rejectRegex"; then
            echo "Java API source manifest line $manifest_line_number has invalid text fields" >&2
            return 1
        fi
        if ! is_absolute_https_remote_base_url "$remoteBaseUrl"; then
            echo "Java API source manifest line $manifest_line_number has an invalid remote base URL" >&2
            return 1
        fi
        if ! is_normalized_relative_mirror_path "$relativeMirrorPath"; then
            echo "Java API source manifest line $manifest_line_number has an invalid relative mirror path" >&2
            return 1
        fi
        if ! is_canonical_manifest_integer "$cutDirectories"; then
            echo "Java API source manifest line $manifest_line_number has invalid cut directories" >&2
            return 1
        fi
        if ! is_canonical_manifest_integer "$minimumHtmlFiles" || [ "$minimumHtmlFiles" = "0" ]; then
            echo "Java API source manifest line $manifest_line_number has invalid minimum HTML files" >&2
            return 1
        fi
        if [ "$allowPartial" != "true" ] && [ "$allowPartial" != "false" ]; then
            echo "Java API source manifest line $manifest_line_number has invalid allow-partial semantics" >&2
            return 1
        fi
        local retained_java_release
        for retained_java_release in "${retained_java_releases[@]}"; do
            if [ "$retained_java_release" = "$javaRelease" ]; then
                echo "Java API source manifest line $manifest_line_number duplicates Java release $javaRelease" >&2
                return 1
            fi
        done
        local retained_relative_mirror_path
        for retained_relative_mirror_path in "${retained_relative_mirror_paths[@]}"; do
            if [ "$retained_relative_mirror_path" = "$relativeMirrorPath" ]; then
                echo "Java API source manifest line $manifest_line_number duplicates mirror path $relativeMirrorPath" >&2
                return 1
            fi
        done

        retained_java_releases+=("$javaRelease")
        retained_relative_mirror_paths+=("$relativeMirrorPath")
        JAVA_API_SOURCE_PROJECTIONS+=("$manifest_line")
    done < "$source_manifest_file"

    if [ -z "$manifest_header" ]; then
        echo "Java API source manifest is empty: $source_manifest_file" >&2
        return 1
    fi
    if [ "${#JAVA_API_SOURCE_PROJECTIONS[@]}" -eq 0 ]; then
        echo "No canonical Java API sources found in $source_manifest_file" >&2
        return 1
    fi
}

append_java_api_fetch_sources() {
    local java_api_source_projection
    for java_api_source_projection in "${JAVA_API_SOURCE_PROJECTIONS[@]}"; do
        DOC_SOURCES+=("$java_api_source_projection")
    done
}

load_documentation_sources() {
    local source_manifest_file="$1"
    if [ ! -f "$source_manifest_file" ]; then
        echo "Documentation source manifest not found: $source_manifest_file" >&2
        return 1
    fi

    DOCUMENTATION_SOURCE_PROJECTIONS=()
    local manifest_header=""
    local expected_delimiter_count=-1
    local manifest_line_number=0
    local manifest_line
    local retained_relative_mirror_paths=("")
    while IFS= read -r manifest_line || [ -n "$manifest_line" ]; do
        manifest_line_number=$((manifest_line_number + 1))
        manifest_line="${manifest_line%$'\r'}"
        if [ "$manifest_line_number" -eq 1 ]; then
            manifest_header="$manifest_line"
            if [ -z "$manifest_header" ]; then
                echo "Documentation source manifest header cannot be blank: $source_manifest_file" >&2
                return 1
            fi
            if [ "$manifest_header" != "$DOCUMENTATION_SOURCE_MANIFEST_HEADER" ]; then
                echo "Documentation source manifest header is invalid: $source_manifest_file" >&2
                return 1
            fi
            local header_delimiters="${manifest_header//[^|]/}"
            expected_delimiter_count=${#header_delimiters}
            continue
        fi
        if is_blank_manifest_line "$manifest_line"; then
            echo "Documentation source manifest line $manifest_line_number cannot be blank" >&2
            return 1
        fi

        local source_delimiters="${manifest_line//[^|]/}"
        if [ "${#source_delimiters}" -ne "$expected_delimiter_count" ]; then
            echo "Documentation source manifest line $manifest_line_number has an invalid column count" >&2
            return 1
        fi

        local fetchUrl
        local citationBaseUrl
        local relativeMirrorPath
        local displayName
        local docSet
        local sourceKind
        local docType
        local docVersion
        IFS='|' read -r fetchUrl citationBaseUrl relativeMirrorPath displayName docSet sourceKind docType docVersion <<< "$manifest_line"

        if [ -z "$fetchUrl" ] \
            || [ -z "$citationBaseUrl" ] \
            || [ -z "$relativeMirrorPath" ] \
            || [ -z "$displayName" ] \
            || [ -z "$docSet" ] \
            || [ -z "$sourceKind" ] \
            || [ -z "$docType" ]; then
            echo "Documentation source manifest line $manifest_line_number has a blank required field" >&2
            return 1
        fi
        if has_boundary_whitespace "$fetchUrl" \
            || has_boundary_whitespace "$citationBaseUrl" \
            || has_boundary_whitespace "$relativeMirrorPath" \
            || has_boundary_whitespace "$displayName" \
            || has_boundary_whitespace "$docSet" \
            || has_boundary_whitespace "$sourceKind" \
            || has_boundary_whitespace "$docType" \
            || has_boundary_whitespace "$docVersion" \
            || has_manifest_control_character "$fetchUrl" \
            || has_manifest_control_character "$citationBaseUrl" \
            || has_manifest_control_character "$relativeMirrorPath" \
            || has_manifest_control_character "$displayName" \
            || has_manifest_control_character "$docSet" \
            || has_manifest_control_character "$sourceKind" \
            || has_manifest_control_character "$docType" \
            || has_manifest_control_character "$docVersion"; then
            echo "Documentation source manifest line $manifest_line_number has invalid text fields" >&2
            return 1
        fi
        if ! is_absolute_https_remote_base_url "$fetchUrl"; then
            echo "Documentation source manifest line $manifest_line_number has an invalid fetch URL" >&2
            return 1
        fi
        if ! is_absolute_https_remote_base_url "$citationBaseUrl"; then
            echo "Documentation source manifest line $manifest_line_number has an invalid citation base URL" >&2
            return 1
        fi
        if ! is_normalized_relative_mirror_path "$relativeMirrorPath"; then
            echo "Documentation source manifest line $manifest_line_number has an invalid relative mirror path" >&2
            return 1
        fi
        local retained_relative_mirror_path
        for retained_relative_mirror_path in "${retained_relative_mirror_paths[@]}"; do
            if [ "$retained_relative_mirror_path" = "$relativeMirrorPath" ]; then
                echo "Documentation source manifest line $manifest_line_number duplicates mirror path $relativeMirrorPath" >&2
                return 1
            fi
        done

        retained_relative_mirror_paths+=("$relativeMirrorPath")
        DOCUMENTATION_SOURCE_PROJECTIONS+=("$manifest_line")
    done < "$source_manifest_file"

    if [ -z "$manifest_header" ]; then
        echo "Documentation source manifest is empty: $source_manifest_file" >&2
        return 1
    fi
    if [ "${#DOCUMENTATION_SOURCE_PROJECTIONS[@]}" -eq 0 ]; then
        echo "No canonical documentation sources found in $source_manifest_file" >&2
        return 1
    fi
}

render_java_javadoc_versions_metadata() {
    local docs_root="$1"
    local metadata_separator=""
    local java_api_source_projection
    for java_api_source_projection in "${JAVA_API_SOURCE_PROJECTIONS[@]}"; do
        local javaRelease
        local remoteBaseUrl
        local relativeMirrorPath
        local displayName
        local cutDirectories
        local minimumHtmlFiles
        local rejectRegex
        local allowPartial
        IFS='|' read -r javaRelease remoteBaseUrl relativeMirrorPath displayName cutDirectories minimumHtmlFiles rejectRegex allowPartial <<< "$java_api_source_projection"
        local javadoc_version
        javadoc_version="$(extract_javadoc_comment_version "$docs_root/$relativeMirrorPath/api/index.html")"
        printf '%s    "java%s_javadoc": "%s"' "$metadata_separator" "$javaRelease" "$javadoc_version"
        metadata_separator=$',\n'
    done
}

render_java_complete_directories_metadata() {
    local docs_root="$1"
    local metadata_separator=""
    local java_api_source_projection
    for java_api_source_projection in "${JAVA_API_SOURCE_PROJECTIONS[@]}"; do
        local javaRelease
        local remoteBaseUrl
        local relativeMirrorPath
        local displayName
        local cutDirectories
        local minimumHtmlFiles
        local rejectRegex
        local allowPartial
        IFS='|' read -r javaRelease remoteBaseUrl relativeMirrorPath displayName cutDirectories minimumHtmlFiles rejectRegex allowPartial <<< "$java_api_source_projection"
        local html_file_count
        html_file_count="$(count_html_files "$docs_root/$relativeMirrorPath")"
        printf '%s    "java%s_complete": "%s"' "$metadata_separator" "$javaRelease" "$html_file_count"
        metadata_separator=$',\n'
    done
}
